// Define team member roles and their colors
export const roleColors = {
  boss: "bg-red-100 text-red-800",
  og: "bg-purple-100 text-purple-800",
  "big brother": "bg-blue-100 text-blue-800",
  brother: "bg-green-100 text-green-800",
  member: "bg-gray-100 text-gray-800",
};

// Define team members data
export const teamMembers = [
  {
    id: 1,
    name: "John Doe",
    role: "boss",
    image: "/team/placeholder.jpg",
    description: "Founder and CEO of Median",
    bio: "John has over 15 years of experience in the tech industry. He founded Median with a vision to create innovative solutions that make a difference in people's lives. His leadership and strategic thinking have been instrumental in the company's growth.",
    quote: "Innovation distinguishes between a leader and a follower.",
    social: {
      twitter: "https://twitter.com/johndoe",
      facebook: "https://facebook.com/johndoe",
      instagram: "https://instagram.com/johndoe",
      linkedin: "https://linkedin.com/in/johndoe",
      github: "https://github.com/johndoe",
    },
  },
  {
    id: 2,
    name: "Jane Smith",
    role: "og",
    image: "/team/placeholder.jpg",
    description: "Co-founder and CTO",
    bio: "Jane is a tech visionary with a background in computer science. She oversees all technical aspects of Median and ensures that we stay at the cutting edge of technology. Her expertise in software architecture has been crucial to our success.",
    quote: "Technology is best when it brings people together.",
    social: {
      twitter: "https://twitter.com/janesmith",
      facebook: "https://facebook.com/janesmith",
      instagram: "https://instagram.com/janesmith",
      linkedin: "https://linkedin.com/in/janesmith",
      github: "https://github.com/janesmith",
    },
  },
  {
    id: 3,
    name: "Mike Johnson",
    role: "big brother",
    image: "/team/placeholder.jpg",
    description: "Lead Developer",
    bio: "Mike leads our development team with his extensive knowledge of modern web technologies. He's passionate about clean code and efficient solutions. Under his guidance, our development team has created robust and scalable applications.",
    quote: "Code is like humor. When you have to explain it, it's bad.",
    social: {
      twitter: "https://twitter.com/mikejohnson",
      facebook: "https://facebook.com/mikejohnson",
      instagram: "https://instagram.com/mikejohnson",
      linkedin: "https://linkedin.com/in/mikejohnson",
      github: "https://github.com/mikejohnson",
    },
  },
  {
    id: 4,
    name: "Sarah Williams",
    role: "big brother",
    image: "/team/placeholder.jpg",
    description: "Design Lead",
    bio: "Sarah brings creativity and user-centered thinking to all our projects. With her background in UX/UI design, she ensures that our products are not only functional but also intuitive and enjoyable to use.",
    quote: "Design is not just what it looks like and feels like. Design is how it works.",
    social: {
      twitter: "https://twitter.com/sarahwilliams",
      facebook: "https://facebook.com/sarahwilliams",
      instagram: "https://instagram.com/sarahwilliams",
      linkedin: "https://linkedin.com/in/sarahwilliams",
      github: "https://github.com/sarahwilliams",
    },
  },
  {
    id: 5,
    name: "David Brown",
    role: "brother",
    image: "/team/placeholder.jpg",
    description: "Senior Developer",
    bio: "David is a seasoned developer with expertise in backend technologies. He's responsible for building and maintaining our server infrastructure and ensuring that our applications run smoothly and securely.",
    quote: "The best code is no code at all.",
    social: {
      twitter: "https://twitter.com/davidbrown",
      facebook: "https://facebook.com/davidbrown",
      instagram: "https://instagram.com/davidbrown",
      linkedin: "https://linkedin.com/in/davidbrown",
      github: "https://github.com/davidbrown",
    },
  },
  {
    id: 6,
    name: "Emily Davis",
    role: "brother",
    image: "/team/placeholder.jpg",
    description: "Marketing Specialist",
    bio: "Emily brings her marketing expertise to help grow our brand and reach new audiences. She develops and implements marketing strategies that align with our company values and goals.",
    quote: "Marketing is about telling good stories.",
    social: {
      twitter: "https://twitter.com/emilydavis",
      facebook: "https://facebook.com/emilydavis",
      instagram: "https://instagram.com/emilydavis",
      linkedin: "https://linkedin.com/in/emilydavis",
      github: "https://github.com/emilydavis",
    },
  },
  {
    id: 7,
    name: "Alex Wilson",
    role: "member",
    image: "/team/placeholder.jpg",
    description: "Frontend Developer",
    bio: "Alex specializes in creating beautiful and responsive user interfaces. With a keen eye for detail and a passion for user experience, he ensures that our applications are not only functional but also visually appealing.",
    quote: "Good design is obvious. Great design is transparent.",
    social: {
      twitter: "https://twitter.com/alexwilson",
      facebook: "https://facebook.com/alexwilson",
      instagram: "https://instagram.com/alexwilson",
      linkedin: "https://linkedin.com/in/alexwilson",
      github: "https://github.com/alexwilson",
    },
  },
  {
    id: 8,
    name: "Lisa Thompson",
    role: "member",
    image: "/team/placeholder.jpg",
    description: "Backend Developer",
    bio: "Lisa is responsible for developing and maintaining the server-side logic of our applications. Her expertise in database design and API development ensures that our applications are fast, secure, and reliable.",
    quote: "Simplicity is the ultimate sophistication.",
    social: {
      twitter: "https://twitter.com/lisathompson",
      facebook: "https://facebook.com/lisathompson",
      instagram: "https://instagram.com/lisathompson",
      linkedin: "https://linkedin.com/in/lisathompson",
      github: "https://github.com/lisathompson",
    },
  },
  {
    id: 9,
    name: "Chris Martin",
    role: "member",
    image: "/team/placeholder.jpg",
    description: "UI/UX Designer",
    bio: "Chris is passionate about creating intuitive and engaging user experiences. He works closely with our development team to ensure that our applications are not only visually appealing but also easy to use.",
    quote: "Design is not just what it looks like and feels like. Design is how it works.",
    social: {
      twitter: "https://twitter.com/chrismartin",
      facebook: "https://facebook.com/chrismartin",
      instagram: "https://instagram.com/chrismartin",
      linkedin: "https://linkedin.com/in/chrismartin",
      github: "https://github.com/chrismartin",
    },
  },
  {
    id: 10,
    name: "Jessica Lee",
    role: "member",
    image: "/team/placeholder.jpg",
    description: "Content Creator",
    bio: "Jessica creates engaging and informative content for our website, blog, and social media channels. Her creative writing skills and understanding of our audience help us connect with our users on a deeper level.",
    quote: "Content is king, but context is god.",
    social: {
      twitter: "https://twitter.com/jessicalee",
      facebook: "https://facebook.com/jessicalee",
      instagram: "https://instagram.com/jessicalee",
      linkedin: "https://linkedin.com/in/jessicalee",
      github: "https://github.com/jessicalee",
    },
  },
  {
    id: 11,
    name: "Robert Taylor",
    role: "member",
    image: "/team/placeholder.jpg",
    description: "QA Engineer",
    bio: "Robert ensures that our applications meet the highest quality standards. His meticulous testing and attention to detail help us identify and fix issues before they reach our users.",
    quote: "Quality is not an act, it is a habit.",
    social: {
      twitter: "https://twitter.com/roberttaylor",
      facebook: "https://facebook.com/roberttaylor",
      instagram: "https://instagram.com/roberttaylor",
      linkedin: "https://linkedin.com/in/roberttaylor",
      github: "https://github.com/roberttaylor",
    },
  },
  {
    id: 12,
    name: "Amanda Clark",
    role: "member",
    image: "/team/placeholder.jpg",
    description: "Project Manager",
    bio: "Amanda oversees our projects from conception to completion. Her organizational skills and ability to coordinate cross-functional teams ensure that our projects are delivered on time and within budget.",
    quote: "A goal without a plan is just a wish.",
    social: {
      twitter: "https://twitter.com/amandaclark",
      facebook: "https://facebook.com/amandaclark",
      instagram: "https://instagram.com/amandaclark",
      linkedin: "https://linkedin.com/in/amandaclark",
      github: "https://github.com/amandaclark",
    },
  },
  {
    id: 13,
    name: "Daniel White",
    role: "member",
    image: "/team/placeholder.jpg",
    description: "DevOps Engineer",
    bio: "Daniel manages our infrastructure and deployment processes. His expertise in automation and continuous integration helps us deliver new features and updates quickly and reliably.",
    quote: "Automate everything that can be automated.",
    social: {
      twitter: "https://twitter.com/danielwhite",
      facebook: "https://facebook.com/danielwhite",
      instagram: "https://instagram.com/danielwhite",
      linkedin: "https://linkedin.com/in/danielwhite",
      github: "https://github.com/danielwhite",
    },
  },
  {
    id: 14,
    name: "Sophia Green",
    role: "member",
    image: "/team/placeholder.jpg",
    description: "Data Analyst",
    bio: "Sophia analyzes user data to help us make informed decisions. Her insights into user behavior and preferences guide our product development and marketing strategies.",
    quote: "Data is the new oil.",
    social: {
      twitter: "https://twitter.com/sophiagreen",
      facebook: "https://facebook.com/sophiagreen",
      instagram: "https://instagram.com/sophiagreen",
      linkedin: "https://linkedin.com/in/sophiagreen",
      github: "https://github.com/sophiagreen",
    },
  },
  {
    id: 15,
    name: "Kevin Adams",
    role: "member",
    image: "/team/placeholder.jpg",
    description: "Mobile Developer",
    bio: "Kevin specializes in developing mobile applications for iOS and Android. His expertise in cross-platform development ensures that our mobile apps provide a consistent experience across different devices.",
    quote: "Mobile is not the future, it is the now.",
    social: {
      twitter: "https://twitter.com/kevinadams",
      facebook: "https://facebook.com/kevinadams",
      instagram: "https://instagram.com/kevinadams",
      linkedin: "https://linkedin.com/in/kevinadams",
      github: "https://github.com/kevinadams",
    },
  },
  {
    id: 16,
    name: "Olivia Baker",
    role: "member",
    image: "/team/placeholder.jpg",
    description: "Customer Support",
    bio: "Olivia is dedicated to providing exceptional support to our users. Her patience and problem-solving skills ensure that our users have a positive experience with our products and services.",
    quote: "Customer service is not a department, it's an attitude.",
    social: {
      twitter: "https://twitter.com/oliviabaker",
      facebook: "https://facebook.com/oliviabaker",
      instagram: "https://instagram.com/oliviabaker",
      linkedin: "https://linkedin.com/in/oliviabaker",
      github: "https://github.com/oliviabaker",
    },
  },
  {
    id: 17,
    name: "Ryan Scott",
    role: "member",
    image: "/team/placeholder.jpg",
    description: "SEO Specialist",
    bio: "Ryan optimizes our website and content for search engines. His strategies help us increase our visibility online and attract more users to our platform.",
    quote: "The best place to hide a dead body is page 2 of Google search results.",
    social: {
      twitter: "https://twitter.com/ryanscott",
      facebook: "https://facebook.com/ryanscott",
      instagram: "https://instagram.com/ryanscott",
      linkedin: "https://linkedin.com/in/ryanscott",
      github: "https://github.com/ryanscott",
    },
  },
  {
    id: 18,
    name: "Natalie King",
    role: "member",
    image: "/team/placeholder.jpg",
    description: "Content Writer",
    bio: "Natalie creates compelling content for our blog and documentation. Her clear and concise writing helps our users understand our products and get the most out of them.",
    quote: "Words have power. Words are power. Words could be your power.",
    social: {
      twitter: "https://twitter.com/natalieking",
      facebook: "https://facebook.com/natalieking",
      instagram: "https://instagram.com/natalieking",
      linkedin: "https://linkedin.com/in/natalieking",
      github: "https://github.com/natalieking",
    },
  },
  {
    id: 19,
    name: "Thomas Hill",
    role: "member",
    image: "/team/placeholder.jpg",
    description: "Graphic Designer",
    bio: "Thomas creates visual elements for our website, marketing materials, and products. His creative designs help us communicate our brand identity and message effectively.",
    quote: "Design is intelligence made visible.",
    social: {
      twitter: "https://twitter.com/thomashill",
      facebook: "https://facebook.com/thomashill",
      instagram: "https://instagram.com/thomashill",
      linkedin: "https://linkedin.com/in/thomashill",
      github: "https://github.com/thomashill",
    },
  },
  {
    id: 20,
    name: "Michelle Parker",
    role: "member",
    image: "/team/placeholder.jpg",
    description: "Social Media Manager",
    bio: "Michelle manages our presence on social media platforms. She creates and curates content that engages our audience and builds our online community.",
    quote: "Social media is not just an activity; it is an investment of valuable time and resources.",
    social: {
      twitter: "https://twitter.com/michelleparker",
      facebook: "https://facebook.com/michelleparker",
      instagram: "https://instagram.com/michelleparker",
      linkedin: "https://linkedin.com/in/michelleparker",
      github: "https://github.com/michelleparker",
    },
  },
];

// Function to get team member data by ID
export const getTeamMemberById = (id: number) => {
  return teamMembers.find(member => member.id === id) || teamMembers[0];
};
